### ISSUE TITLE
FR: Wikipedia style lists.

### ISSUE THREAD

**Issue by spoon-m4a** [Aidurber/obsidian-plugin-dynamic-toc#59]
I really like the Number list style, but I wonder if it would be possible to have it in the Wikipedia style, where you have 1. for your main entry, and children would be prefixed with 1.1, 1.2, etc. I've attached an image for reference

![Number(Wiki style)](https://user-images.githubusercontent.com/104327991/166720595-36128210-7664-4f35-ae56-4892ad08e99a.jpeg)

**Comment by Sandwich1699975** [comment]
For anyone who really likes this feature, you can directly apply this to your whole document with some custom css:

> https://help.obsidian.md/How+to/Add+custom+styles

```css
h2:before {
    counter-increment: h2counter;
    content: counter(h2counter) "\0000a0\0000a0";
}

h3:before {
    counter-increment: h3counter;
    content: counter(h2counter) "." counter(h3counter) "\0000a0\0000a0";
}

h4:before {
    counter-increment: h4counter;
    content: counter(h2counter) "." counter(h3counter) "." counter(h4counter) "\0000a0\0000a0";
}

h5:before {
    counter-increment: h5counter;
    content: counter(h2counter) "." counter(h3counter) "." counter(h4counter) "." counter(h5counter) "\0000a0\0000a0";
}

h6:before {
    counter-increment: h6counter;
    content: counter(h2counter) "." counter(h3counter) "." counter(h4counter) "." counter(h5counter) "." counter(h6counter) "\0000a0\0000a0";
}
```

Which looks like 

<img width="508" alt="image" src="https://user-images.githubusercontent.com/50229842/173174424-2fa5ecc3-683c-40e8-beda-9fe696ce5b51.png">
