### ISSUE TITLE
feature rquest: nested number of TOC 

### ISSUE THREAD

**Issue by hua03** [Aidurber/obsidian-plugin-dynamic-toc#74]
The numbers of child  is independent, like:

```
 1
    1
    2
2
   1
```

Most of the time, I hope they are related, like:

```
1. 
  1.1
  1.2
  1.3
2.
  2.1
  2.2
```

===================

Tips: CSS method `counters` can be used to solve this problem, it is recommended to add an list style `nested number`

```
.dynamic-toc ol {
  counter-reset: tocCounter;
}

.dynamic-toc li {
  counter-increment: tocCounter;
}

.dynamic-toc li::marker {
  content: counters(tocCounter, '.') '  ';
}
```

**Comment by dbarenholz** [comment]
Courtesy of `sailKite#4202` in the discord for another option:

```css
/* inside Dynamic ToC */
.dynamic-toc ol {
    list-style-type: none;
}
.dynamic-toc ol {
    counter-reset: decimal;
}
.dynamic-toc ol > li {
    display: block;
}
.dynamic-toc ol > li::before {
    content: counters(decimal, ".")  " ";
    counter-increment: decimal;
    color: var(--text-a) /* put your text var here or hardcode the color */;
}
```
